/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.me.test;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       //return 'true'", classUnderTest.someLibraryMethod());
    }
}
